-- LOAD DATA LOCAL INFILE 'C:/Users/pranj/Desktop/my code/SQL/Indian General Election 2024 Incidents.csv'
-- INTO TABLE incidents
-- FIELDS TERMINATED BY ','
-- ENCLOSED BY '"'
-- LINES TERMINATED BY '\n'
-- IGNORE 1 ROWS;
